name: Release latest build

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create-release-step.outputs.upload_url }}
    steps:
      - name: Make release
        id: "create-release-step"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest build"

  package-linux:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Linux
        uses: ilesinge/FyneBuildActions/linux@v1
      - name: Rename files
        run: |
          mv Samples4web.tar.xz Samples4web-linux.tar.xz
          mv samples4web samples4web-linux
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: 'Samples4web-linux.tar.xz'
          path: '.'
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: 'samples4web-linux'
          path: '.'
      - name: Add to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./Samples4web-linux.tar.xz
          asset_name: Samples4web-linux.tar.xz
          asset_content_type: application/x-tar
      - name: Add to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./samples4web-linux
          asset_name: samples4web-linux
          asset_content_type: application/octet-stream

  package-windows:
    needs: create-release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install native deps
        run: |
          choco install msys2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Install Fyne CLI
        run: |
          go install fyne.io/fyne/v2/cmd/fyne@latest
          Start-Process -PSPath "$HOME\go\bin\fyne.exe" -ArgumentList "version" -NoNewWindow -Wait
      - name: Install go-msi
        run: choco install -y "go-msi"
      - name: Fyne Package
        run: |
          go generate -v
          Start-Process -PSPath "$HOME\go\bin\fyne.exe" -ArgumentList "package -icon Icon.png" -NoNewWindow -Wait
      # - name: Zip Release
      #   uses: TheDoctor0/zip-release@main
      #   with:
      #     type: 'zip'
      #     filename: 'Samples4web-windows.zip'
      #     path: 'Samples4web.exe'
      # - name: Upload package
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: 'Samples4web-windows.zip'
      #     path: '.'
      - name: Copy exe file
        run: cp Samples4web.exe Samples4web-windows.exe
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: 'Samples4web-windows.exe'
          path: '.'
      - name: Prepare MSI step folder structure
        run: |
          mkdir application
          cp Samples4web.exe application/Samples4web.exe
          cp LICENSE application/LICENSE
          cp Icon.ico application/Icon.ico
      - name: Build Windows Installer MSI from exe file
        uses: AliceOh/CreateWindowsInstaller@1.0.0
        with:
          exefile: 'Samples4web.exe'
      - name: Rename MSI file
        run: ren Samples4web.exe.msi Samples4web-windows.msi
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: 'Samples4web-windows.msi'
          path: '.'
      # - name: Add to release
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ needs.create-release.outputs.upload_url }}
      #     asset_path: ./Samples4web-windows.zip
      #     asset_name: Samples4web-windows.zip
      #     asset_content_type: application/zip
      - name: Add to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./Samples4web-windows.exe
          asset_name: Samples4web-windows.exe
          asset_content_type: application/octet-stream
      - name: Add to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./Samples4web-windows.msi
          asset_name: Samples4web-windows.msi
          asset_content_type: application/octet-stream

  package-mac:
    needs: create-release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Install Fyne CLI
        run: |
          go install fyne.io/fyne/v2/cmd/fyne@latest
          $HOME/go/bin/fyne version
      - name: Install create-dmg
        run: npm install --global create-dmg
      - name: Fyne Package
        run: |
          go generate -v
          $HOME/go/bin/fyne package -icon Icon.png
      - name: Create DMG
        continue-on-error: true
        run: create-dmg Samples4web.app
      - name: Rename DMG
        run: mv "Samples4web 1.0.0.dmg" Samples4web-mac.dmg
      - name: Zip Release
        uses: TheDoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'Samples4web-mac.zip'
          path: 'Samples4web.app'
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: 'Samples4web-mac.zip'
          path: '.'
      - name: Upload DMG
        uses: actions/upload-artifact@v2
        with:
          name: 'Samples4web-mac.dmg'
          path: '.'
      - name: Add to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./Samples4web-mac.zip
          asset_name: Samples4web-mac.zip
          asset_content_type: application/zip
      - name: Add to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./Samples4web-mac.dmg
          asset_name: Samples4web-mac.dmg
          asset_content_type: application/octet-stream
